import type { Metadata } from "next"
import { Geist_Mono, Noto_Sans_SC } from "next/font/google"
import localFont from "next/font/local"

import { TooltipProvider } from "@/components/ui/tooltip"
import { Toaster } from "@/components/ui/sonner"
import { cn } from "@/lib/utils"

import { Layout } from "@/components/layouts/layout"

import "katex/dist/katex.css"
import "./globals.css"

const notoSansSC = Noto_Sans_SC({
  subsets: ["latin"],
  variable: "--font-sans",
})

const geistMono = Geist_Mono({
  subsets: ["latin"],
  variable: "--font-mono",
})

const firaCode = localFont({
  variable: "--font-fira",
  src: [
    {
      path: "./fonts/Fira_Code_v6.2/FiraCode-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/Fira_Code_v6.2/FiraCode-Medium.woff2",
      weight: "500",
      style: "medium",
    },
    {
      path: "./fonts/Fira_Code_v6.2/FiraCode-Bold.woff2",
      weight: "700",
      style: "bold",
    },
  ],
})

// const firaMono = Fira_Mono({
//   subsets: ["latin"],
//   display: "swap",
//   weight: ["400", "700"],
//   variable: "--font-mono",
// })

export const metadata: Metadata = {
  title: "主页 - lorem314.io",
  // description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="zh-CN"
      className={cn(
        "h-full",
        "antialiased",
        notoSansSC.variable,
        geistMono.variable,
        firaCode.variable,
        // firaMono.variable,
        "font-sans-sc",
      )}
      data-scroll-behavior="smooth"
    >
      <body className="flex min-h-full flex-col">
        <TooltipProvider>
          <Toaster richColors />
          <Layout>{children}</Layout>
        </TooltipProvider>
      </body>
    </html>
  )
}
